POINT_MULTIPLIERS = {}
POINT_MULTIPLIERS['PHI LEAGUE'] = {
    'singles' : 1,
    'doubles' : 2,
    'triples' : 3,
    'home runs' : 4,
    'total bases' : 1,
    'walks' : 2,
    'runs scored' : 1,
    'runs batted in' : 1,
    'stolen bases' : 2,
    'strikeouts' : -2,
    'hits' : 1,
    'extra base hits' : 2,
    'game winning rbi' : 3,
    'caught stealing' : -2,
    'ground into double play' : -2,
    'hitting for the cycle' : 10,
    'grand slam home runs' : 4,
    'outfield assist' : 1,
    'errors' : -2,
    'double plays turned' : 1,
    'innings pitched' : 3,
    'earned runs' : -2,
    'wins' : 5,
    'saves' : 5,
    'losses' : -5,
    'blown saves' : -5,
    'strikeouts' : 1,
    'hits allowed' : -1,
    'walks issued' : -1,
    'shutouts' : 5,
    'hit batsmen' : -1,
    'home runs allowed' : -1,
    'wild pitches' : -1,
    'balks' : -5,
    'pick offs' : 3,
    'holds' : 1,
    'complete games' : 5,
    'quality starts' : 2,
    'complete games' : 5,
    'no hitters' : 10,
    'perfect games' : 25
    }
